# .github/workflows/update-directory-reusable.yml
name: Reusable: Update Directory from Template

# このワークフローが他のワークフローから呼び出されることを定義します。
on:
  workflow_call:
    inputs:
      source_repo:
        description: '更新元となるテンプレートリポジトリのURL (例: https://github.com/your-org/template-repo)'
        required: true
        type: string
      target_directory:
        description: '現在のリポジトリ内で更新対象となるディレクトリのパス (例: my-prompts)'
        required: true
        type: string
      branch:
        description: '変更をプッシュするブランチ名'
        required: false
        default: 'main' # デフォルトは 'main' ブランチ
        type: string
    secrets:
      GH_TOKEN:
        description: 'GitHub Personal Access Token (repoスコープが必要)'
        required: true

  # 毎日午前2時 (JST) にこのワークフローを自動実行するスケジュールを設定します。
  # GitHub ActionsのスケジュールはUTCで動作します。
  # 日本時間 (JST) の午前2時は、UTCの前日の午後5時 (17:00 UTC) に相当します。
  schedule:
    - cron: '0 17 * * *' # 毎日 UTC 17:00 (JST 翌日 02:00) に実行

jobs:
  update-target-directory:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへの書き込み権限を付与

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.branch }} # 指定されたブランチをチェックアウト

      - name: Checkout source template repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source_repo }}
          path: ./.template_temp # テンプレートリポジトリを一時ディレクトリにチェックアウト
          token: ${{ secrets.GH_TOKEN }}

      - name: Copy and update directory
        run: |
          TARGET_DIR="${{ inputs.target_directory }}"
          SOURCE_DIR="./.template_temp"

          echo "Updating directory: $TARGET_DIR"

          # 既存のターゲットディレクトリの内容を削除し、完全に置き換えます。
          # !! 注意: この操作はターゲットディレクトリの内容を完全に消去します。
          #          誤ったパスを指定しないよう、十分にご注意ください。
          if [ -d "$TARGET_DIR" ]; then
            echo "Removing existing directory: $TARGET_DIR"
            rm -rf "$TARGET_DIR"
          fi

          echo "Creating directory: $TARGET_DIR"
          mkdir -p "$TARGET_DIR"

          echo "Copying contents from $SOURCE_DIR to $TARGET_DIR"
          # テンプレートリポジトリのルートにあるすべてのファイルとディレクトリをコピー
          cp -r "$SOURCE_DIR"/* "$TARGET_DIR"/
          
          echo "Cleaning up temporary source directory"
          rm -rf "$SOURCE_DIR"

      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          
          # 変更がなければコミットしない
          git add ${{ inputs.target_directory }}
          git diff --cached --exit-code --quiet || \
          (git commit -m "Automated update of ${{ inputs.target_directory }} from ${{ inputs.source_repo }}" && \
           git push origin ${{ inputs.branch }}) || \
           echo "No changes to commit or push."
